- .github/workflows/sync-upstream.yaml
see example in https://github.com/Abirdcfly/ginkgo/pull/6
> feat: add github action to auto-sync upstream

- controllers/organization/predict.go
- pkg/user/annotation.go
> fix: gosec issue

- PROJECT
- api/v1beta1/proposal_types.go
- api/v1beta1/proposal_webhook.go
- api/v1beta1/vote_types.go
- api/v1beta1/vote_webhook.go
- api/v1beta1/webhook.go
- api/v1beta1/webhook_suite_test.go
- config/certmanager/certificate.yaml
- config/default/kustomization.yaml
- config/default/manager_webhook_patch.yaml
- config/default/webhookcainjection_patch.yaml
- config/webhook/manifests.yaml
- pkg/command/operator.go
- pkg/offering/base/proposal/proposal.go
new webhook can be created by command like:`operator-sdk create webhook --group ibp --version v1beta1 --kind Proposal --defaulting --programmatic-validation --verbose --force`.
For #27 
> feat: add webhook

- api/v1beta1/federation.go
- api/v1beta1/organization.go
- api/v1beta1/organization_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/ibp.com_organizations.yaml
- config/rbac/blockchain_cluster_role.yaml
- config/samples/ibp.com_v1beta1_organization_add_client.yaml
- config/samples/ibp.com_v1beta1_organization_remove_client.yaml
- config/samples/ibp.com_v1beta1_organization_transfer_admin.yaml
- config/samples/orgs/org2.yaml
- config/samples/orgs/org3.yaml
- config/samples/readme.md
- config/samples/users/client.yaml
- config/samples/users/client2.yaml
- controllers/organization/predict.go
- controllers/organization/update.go
- pkg/manager/resources/clusterrole/manager.go
- pkg/manager/resources/clusterrolebinding/manager.go
- pkg/manager/resources/role/manager.go
- pkg/manager/resources/rolebinding/manager.go
- pkg/offering/base/organization/mocks/update.go
- pkg/offering/base/organization/organization.go
- pkg/offering/base/organization/override/cluster_role_binding.go
- pkg/offering/base/organization/override/role.go
- pkg/offering/base/organization/override/role_binding.go
- pkg/rbac/rbac.go
- pkg/user/annotation.go
- pkg/user/labels.go
- pkg/user/user.go
Signed-off-by: bjwswang <bjwswang@gmail.com>
Fix: #20
> feat: enable clients(add/remove) and admin(transfer) in crd organization

- controllers/network/predict.go
- controllers/network/update.go
- pkg/offering/base/network/mocks/update.go
- pkg/offering/base/network/network.go
- pkg/user/user.go
> fix: remove network will remove all user annotation

- api/v1beta1/network_types.go
- api/v1beta1/network_webhook.go
- config/samples/ibp.com_v1beta1_network_size_3.yaml
- config/samples/readme.md
- controllers/network/predict.go
- pkg/offering/base/network/network.go
- pkg/offering/base/network/override/order.go
> feat: add network sampele for clusterSize more than one

- api/v1beta1/proposal.go
- controllers/federation/federation_controller.go
- controllers/federation/federation_controller_test.go
- controllers/network/network_controller.go
- controllers/network/network_controller_test.go
- controllers/organization/organization_controller.go
- controllers/organization/organization_controller_test.go
- controllers/proposal/proposal_controller.go
- controllers/vote/vote_controller.go
Signed-off-by: 0xff-dev <stevenshuang521@gmail.com>
feat: more labels on organization cr
https://github.com/bestchains/fabric-operator/issues/32#issuecomment-1370414747
> feat: more labels on organization cr

- api/v1beta1/proposal.go
- api/v1beta1/proposal_types.go
- api/v1beta1/proposal_webhook.go
- config/samples/ibp.com_v1beta1_proposal_dissolve_network.yaml
- config/samples/readme.md
- controllers/federation/predict.go
- controllers/vote/vote_controller.go
> feat: add delete network proposal 

- config/samples/ibp.com_v1beta1_network.yaml
- config/samples/ibp.com_v1beta1_network_size_3.yaml
> fix: network use u4a ingress class

- pkg/initializer/channel/initializer.go
- pkg/initializer/channel/orderer.go
- pkg/initializer/channel/osnadmin.go
Signed-off-by: bjwswang <bjwswang@gmail>
> fix: duplicate ordererorg config in channel group

- .github/workflows/image-build.yaml
> chore: make image build only in bestchain not fork

- controllers/federation/predict.go
- pkg/rbac/synchronizer.go
> fix: rare case of adding multiple identical member

- config/rbac/blockchain_cluster_role.yaml
- config/samples/example-test.sh
- config/samples/users/client.yaml
- config/samples/users/client2.yaml
- config/samples/users/org1admin.yaml
- config/samples/users/org2admin.yaml
- config/samples/users/org3admin.yaml
> feat: use Group to configure common blockchain permissions to users

- config/samples/example-test.sh
- controllers/organization/organization_controller.go
- controllers/organization/predict.go
- controllers/organization/update.go
- pkg/offering/base/organization/mocks/update.go
- pkg/offering/base/organization/organization.go
- pkg/offering/k8s/organization/organization.go
> fix: org status sometimes cannot be changed to Deployed

- api/v1beta1/proposal.go
- config/samples/example-test.sh
- controllers/federation/predict.go
> fix: proposal status get wrong when delete network

- .github/workflows/image-build.yaml
> feat: images adds git tag and date format

- config/samples/example-test.sh
- definitions/organization/admin_role.yaml
- definitions/organization/client_role.yaml
> fix: typos in organization's rbac definition

- config/samples/example-test.sh
Fix example-test timeout in #127 and #123
> fix: example-test timeout

- api/v1beta1/organization.go
- api/v1beta1/organization_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/samples/example-test.sh
- controllers/organization/predict.go
> fix: use string list in organization.status.federation

- pkg/offering/base/channel/channel.go
- pkg/offering/base/channel/peer.go
> fix: skip  channel create & peer join if already did before

- go.mod
- pkg/rbac/synchronizer.go
> fix: rbac update failed because object has been modified

- config/crd/bases/ibp.com_organizations.yaml
- config/samples/example-test.sh
> fix: test peer join status;set ingressnodeip as domain

- pkg/initializer/channel/orderer.go
- pkg/initializer/orderer/configtx/configtx.go
- pkg/initializer/orderer/configtx/default.go
- pkg/offering/base/channel/peer.go
> fix: application channel's configuration has bad settings

- api/v1beta1/channel_webhook.go
- pkg/connector/profile.go
> fix: channel should not be omitted even no peers joined yet;refuse peer join 

- definitions/ca/deployment.yaml
- definitions/console/deployment.yaml
- definitions/orderer/deployment.yaml
- definitions/peer/chaincode-launcher.yaml
- definitions/peer/couchdb-init.yaml
- definitions/peer/couchdb.yaml
- definitions/peer/deployment.yaml
- pkg/offering/base/console/override/deployment.go
> chore: set default ImagePullPolicy to IfNotPresent

- pkg/offering/base/channel/channel.go
- pkg/offering/base/proposal/proposal.go
> fix: set proposal's owner reference to Federation

- api/v1beta1/chaincode_types.go
- api/v1beta1/chaincode_webhook.go
- config/crd/bases/ibp.com_chaincodes.yaml
- config/samples/ibp.com_v1beta1_chaincode.yaml
feat: auto add chaincode label
> feat: auto add chaincode label

- api/v1beta1/organization_webhook.go
> fix: check whether user exits before add/update in organization

- .github/workflows/endtoend-tests.yaml
- pkg/offering/base/peer/override/deployment.go
- sample-network/config/manager/hlf-operator-manager.yaml
- sample-network/config/rbac/hlf-operator-clusterrole.yaml
- sample-network/scripts/cluster.sh
- sample-network/scripts/test_network.sh
> fix: reenable network e2e test

- api/v1beta1/chaincode_types.go
- api/v1beta1/chaincode_webhook.go
- config/crd/bases/ibp.com_chaincodes.yaml
- config/samples/example-test.sh
- config/samples/ibp.com_v1beta1_chaincodebuild_minio.yaml
- config/samples/ibp.com_v1beta1_proposal_create_chaincode.yaml
feat: add ChaincodeBuild/Chaincode test cases in example_test.
Please review this code first. https://github.com/bestchains/installer/pull/46
Fix: https://github.com/bestchains/fabric-operator/issues/161
> feat: add ChaincodeBuild/Chaincode test cases in example_test

- .github/workflows/example-test.yaml
- config/samples/example-test.sh
- controllers/channel/predict.go
- controllers/federation/predict.go
- controllers/proposal/proposal_controller.go
- pkg/offering/base/organization/initializer.go
Fix #202
please merge bestchains/installer#47 first
> feat: use ctr to cache images

- api/v1beta1/proposal.go
> fix: keep same format in Proposal type label

- api/v1beta1/federation_webhook.go
- config/samples/example-test.sh
- controllers/federation/predict.go
> fix: operator restart will cause federation spec error

- .github/auto_request_review.yml
- .github/workflows/auto_assign_reviewers.yml
also need to add https://github.com/actions/first-interaction/issues/10#issuecomment-1475121828
> ci: add auto request review for pr

- pkg/offering/base/chaincode/chaincode.go
> fix: cant get chaincode running status

- api/v1beta1/federation_webhook.go
- api/v1beta1/proposal.go
- api/v1beta1/proposal_webhook.go
- config/samples/example-test.sh
Fix #227
Fix #226 
For bestchains/bc-console#146
> fix: add delete federation member proposal validate

- api/v1beta1/chaincode_webhook.go
- api/v1beta1/proposal_webhook.go
Fix: https://github.com/bestchains/fabric-operator/issues/233
> fix: update the chaincode upgrade conditions

- .github/workflows/integration-tests.yaml
- config/samples/example-test.sh
- config/samples/ibp.com_v1beta1_chaincodebuild_minio.yaml
- config/samples/ibp.com_v1beta1_chaincodebuild_minio_upgrade_chaincode.yaml
- sample-network/scripts/cluster.sh
feat: use the new contract repository bestchains-contracts
Fix: https://github.com/bestchains/installer/issues/66
> feat: use the new contract repository bestchains-contracts
